---
driver:
  name: ec2
  security_group_ids: [ "sg-0e55577a", "sg-7a5c5e0e", "sg-6f57551b", "sg-33a8ec45" ] # jenkins, office
  region: us-east-1
  availability_zone: a
  subnet_id: subnet-24cefe0b # jenkins
  instance_type: ["t3.nano", "t3.micro", "t2.micro"] # in order of preference for bids
  spot_price: "on-demand" # bid up to the on-demand price
  user_data: |
    #!/bin/bash
    killall unattended-upgrades
    killall dpkg
    apt-get purge unattended-upgrades
    rm /var/lib/dpkg/lock-frontend
    ssh-keyscan -H bitbucket.org >> /home/ubuntu/.ssh/known_hosts
  interface: private
  tags:
    Name: test-ansible-wazuh
    env: ms-test

transport:
  max_ssh_sessions: 5
  username: ubuntu
  connection_timeout: 10
  connection_retries: 5
  forward_agent: true
  no-host-key-verify: true

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_host_key_checking: false
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_sudo: true
  idempotency_test: true
  ansible_extra_flags: "-e ansible_python_interpreter=/usr/bin/python3"

platforms:
  - name: ubuntu-20.04

suites:
  - name: default

verifier:
  ruby_bindir: '/usr/bin'

# for your .kitchen.local.yml:
#
# driver:
#   name: vagrant
