---
- name: Add apt keys
  apt_key:
    url: "{{ item }}"
  with_items:
    - https://packages.wazuh.com/key/GPG-KEY-WAZUH
  register: apt_key_result
  until: apt_key_result is succeeded
  retries: 10
  delay: 10

- name: Add Repository
  copy: src=files/wazuh.list dest=/etc/apt/sources.list.d/wazuh.list owner=root mode=0644


- name: install wazuh agent
  apt:
    package:
      - "wazuh-agent"
    update_cache: true
  register: apt_result
  until: apt_result is succeeded
  retries: 10
  delay: 10


- name: Set MANAGER IP
  replace:
    path: /var/ossec/etc/ossec.conf
    regexp: 'MANAGER_IP'
    replace: "127.0.0.1"
  notify:
    - reload systemd
    - restart wazuh daemon
